// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwramfaxcgofrmrzgdpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cmFtZmF4Y2dvZnJtcnpnZHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTM4NjAsImV4cCI6MjA2NTcyOTg2MH0.H1pFjumk4FlyWOoapD3T2lMYXzgubYHr8mx2vvnw6_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);